Repository JustinHuPrime/NPlanetary, pull requests merged in 2021-02, with the labels that each got.

#43 Limit allowed number of players to two
  src/server/Main.hs
Labels: bug

#37 remove makefile
  Makefile
Labels: enhancement

#31 Added list of moves
  src/common/Balance.hs
  src/common/Board.hs
  src/common/Move.hs
Labels: enhancement

#36 Wrote basic client windowing
  NPlanetary.cabal
  hie.yaml
  src/client/Main.hs
  src/client/Networking.hs
  src/client/UI.hs
Labels: enhancement

#67 added basic readme documentation
  CHANGELOG.md
  NPlanetary.cabal
  README.md
  Setup.hs
Labels: documentation, enhancement

#60 Board state sending
  NPlanetary.cabal
  src/client/Networking.hs
  src/common/Board.hs
  src/common/NetInterface.hs
  src/server/Networking.hs
  src/test/TestBoard.hs
  src/test/TestMain.hs
Labels: enhancement

#48 Validate order
  NPlanetary.cabal
  src/common/Balance.hs
  src/common/Board.hs
  src/common/Util.hs
  src/server/Engine.hs
  src/test/TestBoard.hs
  src/test/TestMain.hs
  src/test/TestMove.hs
  src/test/TestOrderValidator.hs
Labels: enhancement

#63 Resolve ticks
  src/common/Board.hs
  src/common/Util.hs
  src/server/Engine.hs
Labels: enhancement

#69 filter out multiple thrust/attack orders per ship
  src/server/Engine.hs
Labels: bug

#72 add simple initial board for two players
  src/common/Board.hs
  src/server/Main.hs
Labels: enhancement

#71 Added initial board rendering
  NPlanetary.cabal
  hie.yaml
  src/client/Main.hs
  src/client/Renderer.hs
  src/client/Theme.hs
  src/client/UI.hs
Labels: enhancement

#76 Rest of the UI
  NPlanetary.cabal
  hie.yaml
  src/client/Interaction.hs
  src/client/Main.hs
  src/client/Renderer.hs
  src/client/Theme.hs
  src/client/UI.hs
  src/server/Main.hs
Labels: enhancement
